### ISSUE TITLE
Usar String Interpolation 

### ISSUE THREAD

**Issue by NobreMateus** [JMateusSousa/CBL-Guide#1]
Minha sugestão é na linha 30 do arquivo Application.swift:

onde tem
fileReader.access(filename: "GuiaCBL" + String(screen) + String(topic) + ".txt")

poderia ser substituido para se usar String Interpolation e deixar o código mais legível, da seguinte forma:
fileReader.access(filename: "GuiaCBL \(String(screen)) \(String(topic)).txt")

**Comment by JMateusSousa** [comment]
Pronto, sua sugestão foi bem recebida e foi implementada. 
Logo essa versão terá seu commit.
